#!/bin/sh
umask 077

answers() {
	echo CH
	echo Beijing
	echo Beijing
	echo Litevirt.com
	echo Litevirt.com
	echo localhost.localdomain
	echo root@localhost.localdomain
}

if [ $# -eq 0 ] ; then
	echo $"Usage: `basename $0` target [...]"
	exit 0
fi

for target in $@ ; do
	answers | /usr/bin/openssl req -newkey rsa:4096 -keyout $target.pem -nodes -x509 -days 365 -out $target.cert 2> /dev/null
done
